### ISSUE TITLE
java.lang.IllegalStateException: NDatabase has not loaded yet

### ISSUE THREAD

**Issue by apollyon600** [NivixX/NDatabase#11] opened 2024-02-20 15:15 UTC
I came across NDatabase and it looked like it had everything that I needed. 
Decided to test it out but whenever I try to call the API of NDatabase, it always says it wasn't loaded. 
I looked at logs and it seems like it had successfully connected to mongo, but no matter how long I wait to use the API, it says it hasn't been loaded.

I even compiled my own version of NDatabase that logs the exact moment of when the api had successfully been loaded via reflection, but to my own avail, it still isn't working.

**Comment by NivixX** [comment] 2024-02-22 01:19
Hello, do you have any exception ? The NDatabaseAPI instance is indeed set using reflection to avoid exposing a set method, if something wrong happened with reflection, you should see a _'Failed to load NDatabase...'_ exception.
If not, maybe the resolved instance is null for some reason (I use Google Guice for dependency injection).

You can try to do that:

- Verify if no exception is thrown.
- Log the NDatabase resolved instance and check if it's null.
- You can also try to run your server only with NDatabase + your plugin.

Here is where you can add logging
[https://github.com/NivixX/NDatabase/blob/main/ndatabase-core/src/main/java/com/nivixx/ndatabase/core/PlatformLoader.java#L81](https://github.com/NivixX/NDatabase/blob/main/ndatabase-core/src/main/java/com/nivixx/ndatabase/core/PlatformLoader.java#L81)

Let me know what is your Java/Spigot version so if your issue is not solved I can try to reproduce when I'm free.

**Comment by Hellcode48** [comment] 2024-03-22 06:44
I'm having the same issue on 1.20.4.

I did everything correct, there's no errors at all

**Comment by NivixX** [comment] 2024-03-22 10:30
> I'm having the same issue on 1.20.4.
> 
> I did everything correct, there's no errors at all

Hello, If you could test with only NDatabase and your plugin and telling me what java version and what spigot fork you use, it would help me. I'm trying to reproduce the issue with paperSpigot 1.20.4 with java 17 and I don't have the issue

**Comment by Hellcode48** [comment] 2024-03-22 18:53
> > I'm having the same issue on 1.20.4.
> > I did everything correct, there's no errors at all
> 
> Hello, If you could test with only NDatabase and your plugin and telling me what java version and what spigot fork you use, it would help me. I'm trying to reproduce the issue with paperSpigot 1.20.4 with java 17 and I don't have the issue

I can't really only test with it because my plugin requires a few other plugins. Here's my code, lmk if I'm doing something wrong.

It's 1.20.4 Paper Spigot Java 17

https://pastebin.com/m0JjqZJ8

https://pastebin.com/cD7q8ddn

https://pastebin.com/8gqgrjJ8

It's been a few years since I coded java so I'm not sure if I'm doing anything correctly lol

**Comment by NivixX** [comment] 2024-03-24 13:55
> > > I'm having the same issue on 1.20.4.
> > > I did everything correct, there's no errors at all
> > 
> > 
> > Hello, If you could test with only NDatabase and your plugin and telling me what java version and what spigot fork you use, it would help me. I'm trying to reproduce the issue with paperSpigot 1.20.4 with java 17 and I don't have the issue
> 
> I can't really only test with it because my plugin requires a few other plugins. Here's my code, lmk if I'm doing something wrong.
> 
> It's 1.20.4 Paper Spigot Java 17
> 
> https://pastebin.com/m0JjqZJ8
> 
> https://pastebin.com/cD7q8ddn
> 
> https://pastebin.com/8gqgrjJ8
> 
> It's been a few years since I coded java so I'm not sure if I'm doing anything correctly lol

You are using the API correctly, therefore I'm not able to reproduce the issue with Java 1.20.4 and java 17
I did a small change that do some inforce and change dependency injection method, you can try
https://github.com/NivixX/NDatabase/releases/tag/1.2.1

**Comment by Pilvinen** [comment] 2024-10-26 10:09
I'm having this same issue or similar issue. Everything was working fine in Spigot Minecraft 1.21.1, but then I updated to 1.21.3. I tried to revert back to 1.21.1, but for some reason it's still utterly broken. I tried deleting the config and database, but even that didn't work. NDatabase does not throw any errors, it seems to think everything is fine.

On trying to load my code it becomes apparent that everything is not fine:

```
[13:00:25] [Server thread/ERROR]: Error occurred while enabling CriticalFixes v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: NDatabase has not loaded yet
at com.nivixx.ndatabase.api.NDatabase.api(NDatabase.java:22) ~[?:?]
at starandserpent.minecraft.criticalfixes.BetterTrapdoors.<init>(BetterTrapdoors.java:33) ~[?:?]
at starandserpent.minecraft.criticalfixes.CriticalFixes.registerBetterTrapdoors(CriticalFixes.java:397) ~[?:?]
at starandserpent.minecraft.criticalfixes.CriticalFixes.onEnable(CriticalFixes.java:90) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:576) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:490) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
```

And nothing works after that. It's completely dead. Nothing gets saved to the database. No further errors, though.

I'm not sure how to proceed. I tried to revert back to earlier version of NDatabase, but that didn't work either.

Spigot 1.21.1
Java 22
NDatabase 1.3.0-1.3.2

**Comment by Pilvinen** [comment] 2024-10-26 10:37
I tried all NDatabase versions all the way back to 1.1.7 and they now suffer from the same issue.
I can only conclude that it must be something in later versions of Spigot or Java. Everything was working fine with zero changes made to my code and it's ultimately the updating that broke it for me. I went without updates for about 6 months. I think I was 43 versions behind on Spigot MC 1.21.1. I can't really go back to earlier version than that. I'm not sure what to do at this point. I have a half mind set on just giving up and closing the whole Minecraft server because of this. I have NDatabase integrated pretty tightly into everything and pretty much nothing works without it.
Such a headache.

**Comment by Pilvinen** [comment] 2024-10-27 14:28
Present also in NDatabase-1.4.0.

**Comment by NivixX** [comment] 2024-10-28 01:00
Hi @Pilvinen I'll try with java 22 and your spigot version, I'm pretty sure it's because of google guice library that has conflict to specific JVM or the server software you're using. I will eventually get rid of this google guice as it's causing so many potential conflicts.
I'll back to you soon.

**Comment by NivixX** [comment] 2024-10-28 01:16
@Pilvinen Could you also confirm that in your plugins that are using NDatabase, you added depency in the plugin.yml

`depend: [NDatabase]`

**Comment by NivixX** [comment] 2024-10-28 15:34
I tried to reproduce the issue using the same spigot version as you and java 22, with a simple plugin that access NDatabase.api() instance on load, and unfortunately I don't have the issue.

However, I added more logs and enforcement to ensure NDatabase plugin doesn't load if the api instance is null.
You can try this version https://github.com/NivixX/NDatabase/releases/tag/1.4.1

If possible test with NDatabase (only), and then with one plugin that use NDatabase. You should have the following message before being usable:
`NDatabase platform (bukkit) has been loaded with success and the api is usable.`

**Comment by Pilvinen** [comment] 2024-10-28 15:46
> I tried to reproduce the issue using the same spigot version as you and java 22, with a simple plugin that access NDatabase.api() instance on load, and unfortunately I don't have the issue.
> 
> However, I added more logs and enforcement to ensure NDatabase plugin doesn't load if the api instance is null. You can try this version https://github.com/NivixX/NDatabase/releases/tag/1.4.1
> 
> If possible test with NDatabase (only), and then with one plugin that use NDatabase. You should have the following message before being usable: `NDatabase platform (bukkit) has been loaded with success and the api is usable.`
> 
> Let me know the full log to have better idea of what's going on

[17:38:11] [Server thread/INFO]: [NDatabase] Enabling NDatabase v1.4.1
[17:38:11] [Server thread/WARN]: [NDatabase] Could not save config.yml to plugins/NDatabase/config.yml because config.yml already exists.
[17:38:12] [Server thread/INFO]: NDatabase platform (bukkit) has been loaded with success and the api is usable.

But then, at 17:38:14:

[17:38:14] [Server thread/ERROR]: Error occurred while enabling CriticalFixes v1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: NDatabase has not loaded yet. Verify that your plugin configuration include NDatabase in dependencies.
at com.nivixx.ndatabase.api.NDatabase.api(NDatabase.java:22) ~[?:?]
at starandserpent.minecraft.criticalfixes.CauldronImprovements.<init>(CauldronImprovements.java:30) ~[?:?]
at starandserpent.minecraft.criticalfixes.CriticalFixes.registerCauldronImprovements(CriticalFixes.java:209) ~[?:?]
at starandserpent.minecraft.criticalfixes.CriticalFixes.initializePlugin(CriticalFixes.java:60) ~[?:?]
at starandserpent.minecraft.criticalfixes.CriticalFixes.onEnable(CriticalFixes.java:31) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:576) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:490) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4344-Spigot-a759b62-19bf846]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

And that's the end of that. Nothing works. Database file has nothing in it (I backed up and deleted the old one, just in case). Zero bytes.

It's weird because it has been working just fine for half a year. And I haven't touched any of my code. So something broke in the Minecraft update and reverting back didn't help, and I can't figure out what might be going wrong. It's against all logic.

Here's the full Spigot log, but there's nothing particularly interesting in it sans the parts above:
https://pastebin.com/f8BuGVXS

If you'd like, and you have some ideas what it might be, I could try running a special version for you with more debug information exposed.

**Comment by Pilvinen** [comment] 2024-10-28 16:02
I don't suppose anything has changed in the API?

I have NDatabase as requirement in the plugin.yml:

```
name: CriticalFixes
version: '${project.version}'
main: starandserpent.minecraft.criticalfixes.CriticalFixes
api-version: '1.20'
depend: [ ProtocolLib, NDatabase ]
softdepend: [ Tooltips ]
```
Etc.

Then from my plugin's entry point `CriticalFixes.java` I override `onEnable`:

```
@Override public void onEnable() {
    initializePlugin();
}
```

Which calls, for example, `registerCauldronImprovements();` which, I suppose, is the first thing trying to access NDatabase (If I comment it out then the next thing breaks and so on).

It has:

```
    private void registerCauldronImprovements() {
        System.out.println("CriticalFixes: Loading CauldronImprovements.");
        var cauldronImprovements = new CauldronImprovements(this);
        pluginManager.registerEvents(cauldronImprovements, this);
    }
```

And in the CauldronImprovements:

```
public class CauldronImprovements implements Listener {

    private final JavaPlugin plugin;
    private Server server;

    Repository<UUID, CauldronLocation> repository;

    public CauldronImprovements(JavaPlugin plugin) {
        this.plugin = plugin;
        this.server = plugin.getServer();

        // Get the NDatabase repository.
        repository = NDatabase.api().getOrCreateRepository(CauldronLocation.class);
}
```

And on top of that it has just couple event handlers, so I think it must break when I try to access `NDatabase.api().getOrCreateRepository(CauldronLocation.class);` in the constructor.

Am I doing something obviously wrong?

**Comment by NivixX** [comment] 2024-10-28 16:15
[plugins.zip](https://github.com/user-attachments/files/17545539/plugins.zip)

Indeed, that's very weird, given that we can see that the NDatabase load correctly.
From the code you provided I don't see anything wrong, and once NDatabase is loaded, you should be able to call NDatabase.api() anyhow you want.

NDatabase rely on some dependency injection mechanism and also use Google Guice, so one possibility is that some bad reflection magic is happening.

Let's break this down together and process step by step.

First, I would like to verify is there is no weird stuff happening related to how your plugin .jar is built.
I have made a very simple plugin that access api() on load (NDatabaseTest), please try NDatabase with NDatabaseTest and let me know if you have an error.

Second, as I suspect Guice, I have made a version of NDatabase without Guice, you can try it (it's lighter than the original NDatabase).

Let me know when you have any updates

**Comment by Pilvinen** [comment] 2024-10-28 16:32
Ah, hm. Here's my pom.xml for Maven in case there's something useful in there:

https://pastebin.com/kFbjJ3WT

**Comment by NivixX** [comment] 2024-10-28 16:35
Would you mind sharing the .jar, or first, could you verify that in the .jar of your plugin, there is no com.nivixx.ndatabase package and files ?

I see that you use shading plugin, so if you are including NDatabase classes and you call NDatabase.api() from your plugin, it will actually not call the "Singleton" NDatabase that is loaded in NDatabase plugin, but a "shaded" version of the NDatabase.api(). That could explain the issue, let me know if it's your case

**Comment by NivixX** [comment] 2024-10-28 16:44
note: you can exclude ndatabase in your .jar with the shade plugin or setting the scope as provided.

<dependency>
    <groupId>com.github.NivixX</groupId>
    <artifactId>ndatabase-api</artifactId>
    <version>1.4.1</version>
    <scope>provided</scope>
</dependency>

**Comment by Pilvinen** [comment] 2024-10-28 17:00
I think the reason why I've originally provided the local package is because I can't get it working with "scope provided" by using what you've shown me there just now - nor with the instructions in the official docs which differ a little bit from what you just showed me there.

I don't fully understand the shadowing issue either and why it didn't happen before, but okay (not an expert on Java).

I would of course prefer to get the package from the interwebs using "scope provided", but I'm getting:

> com.github.NivixX:ndatabase-api:pom:1.4.1 failed to transfer from https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer artifact com.github.NivixX:ndatabase-api:pom:1.4.1 from/to jitpack.io (https://jitpack.io): status code: 401, reason phrase: Unauthorized (401)

**Comment by NivixX** [comment] 2024-10-28 17:17
In my previous message with the pom.xml I did miss "NDatabase" in the package name,
the correct pom is

```
<dependency>
    <groupId>com.github.NivixX.NDatabase</groupId>
    <artifactId>ndatabase-api</artifactId>
    <version>1.4.1</version>
    <scope>provided</scope>
</dependency>
```

Glad your issue is fixed, both adding a "provided" scope or excluding the package will work (it does the same actually).

By default, when you use this shade plugin, every dependencies that has scope "compile" (default value), will be compiled inside your .jar plugin with prefix.
To take the example of NDatabase, what happens is that it copy paste the .class of NDatabase into "starandserpent.minecraft.criticalfixes.com.nivixx.ndatabase.*", so when you call NDatabase.api(), it call this class and not the original class from the loaded plugin.

I see that you are using protocolib, and you have the scope to provided to avoid having the protocolib source code mixed in your .jar

Anyway, I will also update the doc to make it more clear in case of using shading maven plugin, thank you !

**Closed** 2024-10-29 11:03 UTC
Labels: bug
